# Generated by Django 4.1.2 on 2022-11-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('albumId', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dominant_color', models.CharField(max_length=6)),
            ],
        ),
    ]
